### ISSUE TITLE
Update chrome store images

### ISSUE THREAD

**Issue by Geczy** [JustBuild/Project-Axeman#108]
https://chrome.google.com/webstore/detail/project-axeman/jdpilgbpoogpebhhfbbgpaebkndebmee?hl=en

That's a very old Travian version, could use an update to attract more people. They might think it only works on T3 and below

**Comment by Geczy** [comment]
Here's the new images https://imgur.com/a/S98s1

**Comment by AleksandarDev** [comment]
Thanks

**Comment by AleksandarDev** [comment]
@Geczy Images are updated and the new version is published (1.0.2 cause I deployed without submodules twice :D) Check it out.

**Comment by Geczy** [comment]
We are still linking to the old images on the github pages https://justbuild.github.io/Project-Axeman/

Is that site still being used in places other than the chrome extension store "Website" link?

**Comment by AleksandarDev** [comment]
Only on store as far as I know. I was looking at it too today, the thing doesn't look that good :D 

Update or delete the site?

**Comment by Geczy** [comment]
Delete and just link to the github repo. We will keep the readme updated instead
