### ISSUE TITLE
Remove upgrade indicators

### ISSUE THREAD

**Issue by Geczy** [JustBuild/Project-Axeman#128]
Travian now includes these by default

**Comment by AleksandarDev** [comment]
Aren't upgrade indicator just partial? I don't think they have all features we have?

**Comment by Geczy** [comment]
Partial in what way? It turns green if it's upgradeable, otherwise it's yellow

**Comment by AleksandarDev** [comment]
Yeah, but you don't know of you have enough resources to upgrade...

**Comment by Geczy** [comment]
You do when it turns green (travian feature)

**Comment by Geczy** [comment]
Here's an example, notice green vs yellow. We could remove all the calculations and just extend the default colors to make them more visible 

![](http://i.imgur.com/3OZIfui.png)

**Comment by AleksandarDev** [comment]
Yeah, that would be great. I was not aware of the new feature. 
We currently check for: (do they)
- [ ] crop lock
- [ ] storage limit 
- [x] resource available limit
- [x] upgrading...
- [x] max level
Could you check for that cases too? (ofc, when you get to that level)

**Comment by Geczy** [comment]
>Village: Resource fields and buildings now show if they are actually upgradeable by showing a green ring around their level.	

This is all I found in the changelog

Sure I will check the other things, might take a month

**Comment by AleksandarDev** [comment]
Sure, thanks. If we don't get feedback before that i think it's best to just disable that plugin by default.

Link to another issue https://github.com/JustBuild/Project-Axeman/issues/124

**Comment by AleksandarDev** [comment]
I have now checked this. Our indicators work even if you have building queue full. We should instead change design to that level number is visible and implement your building queue.
