### ISSUE TITLE
Remove numbered alliance members

### ISSUE THREAD

**Issue by Geczy** [JustBuild/Project-Axeman#129]
Travian has this by default

**Comment by AleksandarDev** [comment]
@Geczy I know, that's why I created this issue, that feature is redundant in our plugin. 

I'm currently waiting for T5 release, then I'll continue development.

**Comment by AleksandarDev** [comment]
@Geczy nvm, I was sure i already created this issue. I guess it was just a dev-note, not an issue.

**Comment by Geczy** [comment]
You've seen the beta for T5 right? It's dramatically different, might want to keep this branch and open a new branch for T5. Maybe include both versions in one plugin with auto detection

**Comment by AleksandarDev** [comment]
Sure thing. Core/Services currently checks for travian version for crawling. This could be implemented for Plugins too. So that plugins auto-select what UI to show.

**Comment by AleksandarDev** [comment]
Did you think of more like forking this and creating separate code for T5 and then bootstrap right version when on travian page?

That would be interesting too...

**Comment by Geczy** [comment]
Yes that might be necessary because of how different the versions are, but we will see
