### ISSUE TITLE
Travian plus buttons

### ISSUE THREAD

**Issue by Geczy** [JustBuild/Project-Axeman#136]
![](http://i.imgur.com/iFSEv5k.png)

I wanna make these work. Thoughts on bannability? Can just appeal and say you were using browser bookmarks if they ever ask?

**Comment by AleksandarDev** [comment]
Yeah, we could do that, but we would need to create some kind of notice explaining people that they should say that if asked. 
Alternative would be to navigate by multiple requests.

**Comment by AleksandarDev** [comment]
@Geczy You already have branch with that feature

I have added you back to the project so that you can push to your branches
