### ISSUE TITLE
[User feedback] Hadi Bazmi feature reqests

### ISSUE THREAD

**Issue by AleksandarDev** [JustBuild/Project-Axeman#156]
Wednesday, May 6, 2015 11:55 PM

```
hi, first of all it is a great extension but some notes: 1- the color of indicators dont make any sense :| (at least on my vills)
2-could you add a mass auto add to farm list? from an excel file or something?
3- in barracks and stable please make the res callculator alive, which calculate ressoursec as we set a number in the box
5-all the number of resource needed (which are in red color) are diffrent from actual number
tnx
```

You can continue discussion here.

**Comment by Geczy** [comment]
1. indicator colors make perfect sense to me
2. not at this time
3. the res calculator exists in barracks and stable 
![image](https://user-images.githubusercontent.com/1036968/30597632-91b7608c-9d25-11e7-9fa3-15a4c1963ce4.png)
4. the red number is correct, it's not the amount needed for the troop, its the amount needed for the troop MINUS the amount of resources you own

**Comment by AleksandarDev** [comment]
👍
