### ISSUE TITLE
Marketplace resource send helper

### ISSUE THREAD

**Issue by Geczy** [JustBuild/Project-Axeman#157]
When sending resources to your village, the "Full" button should note how much resources you actually have before filling the numbers. Currently it tries to send more than you have

**Comment by AleksandarDev** [comment]
I haven't maintained this extension for couple of years now, does this extension still work?

**Comment by AleksandarDev** [comment]
This is a known issue #121

**Comment by Geczy** [comment]
Check the latest commits ;)

**Comment by AleksandarDev** [comment]
@Geczy Oh nice :D let me know when it's ready for update on chrome store. I currently don't play Travian so I can't test these.

**Comment by Geczy** [comment]
Make an account :) https://tx3.travian.us/

**Comment by Geczy** [comment]
https://github.com/JustBuild/Project-Axeman/issues/108

I think it is ready now, you can use the images here

**Comment by Geczy** [comment]
This add page still doesn't do anything, it is confusing to users so I may remove it first

![image](https://user-images.githubusercontent.com/1036968/30605280-7ffb55b8-9d3b-11e7-9116-3d62b45b8208.png)

**Comment by Geczy** [comment]
Fixed that bug, it is ready now..

**Comment by AleksandarDev** [comment]
The add profile feature was some kind of a shortcut for your profiles. It did work as expected for me... don't know when it broke. It's not essential, can be removed if not working.

**Comment by Geczy** [comment]
Yah maybe it should be removed since the plugin automatically adds profiles anyway
