### ISSUE TITLE
Plugin settings

### ISSUE THREAD

**Issue by AleksandarDev** [JustBuild/Project-Axeman#99]
- Setting model
  - Model types: boolean, number, string, color (for now)
- Plugin template to support settings
- Apply settings to existing plugins
  - [x] UpgradeIndicator https://github.com/JustBuild/Project-Axeman/pull/114
  - [x] ResourceCalculator https://github.com/JustBuild/Project-Axeman/pull/114
  - [ ] ResourceIndicator
  - [x] ResourceSender _(no custom settings)_
  - [ ] Decorations
  - [x] AutoAdventure _(no custom settings)_
  - [ ] MarketplaceEnhancements
  - [ ] TravianPLUS
  - [ ] VillageListEnhancement

**Comment by Geczy** [comment]
Not every plugin needs their own settings, I say we create an issue as we find a plugin that does need to be customized by the user

**Comment by AleksandarDev** [comment]
Agree
